import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Prueba SSR <a href="">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/dynamics/id.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/dynamics/documentation" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            
          </a>

          <a href="/dynamics/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
          </a>

          <a
            href="/dynamics/example"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
          </a>

          <a
            href="/dynamics/deploy"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
